### PR TITLE
Add environment variables to define directories

### PR DESCRIPTION
**Pull request by thucke**
Hi Martin,

these changes add three optional environment variables to gain more control of the directories:

- T3DOCS_SOURCE
- T3DOCS_TARGET
- T3DOCS_WEBROOT

It will solve the issue I mentioned on slack when starting the rendering container an the docker host from within another container. Perhaps the same issue will arise when starting it from another docker host.

### CODE REVIEW

**Comment by thucke** [comment]
Another bug found.
Next commit will be quality tested from out of a Jenkins docker instance.

**Comment by thucke** [comment]
The following script successfully triggered by a Jenkins instance within a running docker container on the same host. A step before did the checkout of my Git repository into the path `T3DOCS_SOURCE` on the host (wich is also a shared directory)

```

#!/bin/bash
set -x

T3DOCS_EXTERNAL_MOUNT="/mnt/external"
T3DOCS_HOST_MOUNT="/volume1/docker/Jenkins/dockermounts/external"
T3DOCS_TARGET_ROOT="t3docs"
T3DOCS_SOURCE="/volume1/docker/Jenkins/dockermounts/external/git/TYPO3.ext.th_rating"
T3DOCS_FORCE_WEBROOT=1

source <(docker run --rm t3docs/render-documentation:1.6.5 show-shell-commands)
dockrun_t3rdf makehtml
```

**Comment by marble** [comment]
Hi Thomas @thucke , I'll look at this the next time I work on this project.

**Comment by marble** [comment]
Hello Thomas, thank you very much for your pull request. I read through it carefully and I think I have now implemented all the desired functionality. Yes, it's definitely something desireable. I picked up your ideas but not the code. Please read through the README of tags v1.6.9-full and v1.6.9-html. Would be nice to here from you if it works for you. A follow up comment here seems fine!

**Comment by thucke** [comment]
Hi @marble ,
please apologize my late response.

I had to struggle around a bit to get it running. But finally it runs!
Let me tell you the details .... perhaps also for others ....

My Jenkins container:
(in real I'm using a self customized Dockerfile which is based upon the original one)
```
docker run --name="ThuckeJenkins-2.107.1" \
-p 8085:8080 -p 50000:50000 \
-v jenkins_home:/var/jenkins_home \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /usr/local/bin/docker:/usr/bin/docker \
-v /volume1/docker/Jenkins/dockermounts/external:/mnt/external \
-e "DOCKER_GID_ON_HOST=0" \
jenkins/jenkins:2.107.1
```

You see from inside the Jenkins container the data is stored in `/mnt/external`.
From outside the container the data is stored in `/volume1/docker/Jenkins/dockermounts/external`.
The docker daemon sees the later directory.

This script is being called by the Jenkins job after a git checkout to `/mnt/external/t3docs/git` (from within the container which is `/volume1/docker/Jenkins/dockermounts/external/git` from outside)
```
#!/bin/bash
set -x

T3DOCS_PROJECT="/volume1/docker/Jenkins/dockermounts/external/git/TYPO3.ext.th_rating"
T3DOCS_RESULT="/mnt/external/t3docs"
source <(docker run --rm t3docs/render-documentation:v1.6.10-html show-shell-commands)

T3DOCS_RESULT="/volume1/docker/Jenkins/dockermounts/external/t3docs"
dockrun_t3rdh makehtml
```

The issue I had to cope with is that in my original script the 'source'-command runs good but the final commands failed.
This obviously was reasonably caused by that the environment of the running container changed in terms that `T3DOCS_RESULT` has to be set to "outside view".

Thank you a lot following up my suggestion.



Anyway does it make sense to rename the generated command from `dockrun_t3rdf` to `dockrun_t3rdh` in this variant?
From my point of view people are using either one of both variants not both which could be a point to distinguish the commands. If it is really needed I'd like to suggest to extend the documentation in both variants pointing out this difference.

**Comment by marble** [comment]
About the names `dockrun_t3rdf` and more names: Yes, I'm not happy with the current state and struggeling with that, but I wanted to put the new working state online. Will improve that next time.

In your case (I don't understand all of it I guess) you may want to run the explicite Docker command. After all, `dockrun_t3rdf ()` is just a convenience function that translates into the final, explicite Docker run command. You should find that in `Documentation-GENERATED-temp/last-docker-run-command-GENERATED.sh`.

**Comment by marble** [comment]
I forgot to say: Once you got it running perfectly - it would be cool if we could add a little How-to to the project. Maybe you want to drop me a - german - line @ martin.bless@typo3.org

**Comment by thucke** [comment]
Hmm, the documentation still does not get rendered - even not in "normal" mode.
The file `tmp-GENERATED-temp\RenderDocumentation\2018-06-10_15-03-59_607349\TheProjectLog\html\warnings.txt` provides the following information:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python2.7/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxcontrib.slide (exception: cannot import name Directive)

Extension error:
Could not import extension sphinxcontrib.slide (exception: cannot import name Directive)
```
Could there be an issue with the docker image in dockerhub?
I tried both versions (html & full).

**Comment by thucke** [comment]
Hmm, the documentation still does not get rendered - even not in "normal" mode.
The file `tmp-GENERATED-temp\RenderDocumentation\2018-06-10_15-03-59_607349\TheProjectLog\html\warnings.txt` provides the following information:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python2.7/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxcontrib.slide (exception: cannot import name Directive)

Extension error:
Could not import extension sphinxcontrib.slide (exception: cannot import name Directive)
```
Could there be an issue with the docker image in dockerhub?
I tried both versions (html & full).

**Comment by thucke** [comment]
Hi @marble ,
wouldn't it be feasible reopening this issue?
Or might you want to open a new one?

**Comment by marble** [comment]
For whatever reasons Github doesn't offer "reopen" to me. So feel free to create another issue.
Please attach you Settings.cfg file.
Is this the version you see:```
➜  ~ dockrun_t3rdf 
t3rdf - TYPO3 render documentation full (v1.6.10-full)
For help:
   docker run --rm t3docs/render-documentation:v1.6.10-full --help
   dockrun_t3rdf --help

... did you mean 'dockrun_t3rdf makehtml'?
```

**Comment by thucke** [comment]
I've already confugured a settings.yml.
You may find my repository at https://github.com/thucke/TYPO3.ext.th_rating/tree/master/Documentation.
Here's the file itself: [Settings.zip](https://github.com/t3docs/docker-render-documentation/files/2130961/Settings.zip)

... and finally:
Yes, this version is exaclty what I see.

**Comment by marble** [comment]
Please drop this line:
image

If I remember correctly ("mir dämmert gerade ...") this is what happens. The container now uses a newer version of Sphinx. With that version some of the Sphinx extensions don't work any more at the moment. And that "slide" extension is one of them. You probably don't need it. See https://github.com/sphinx-contrib/slide

image

**Comment by thucke** [comment]
Hmm, perhaps a step forward. But still an issue.
After I did as you suggested my documentation still was not generated.
Then I've removed all of the extension but the documentation won't be generated.
There's a message which could give you a hint?:
grafik
Is that REBUILD_NEEDED part normal?

**Comment by marble** [comment]
We should talk. I contacted you on Slack.
The REBUILD_NEEDED is normal.

What you can do: create folder `tmp-GENERATED-temp` at the same level of `Documentation`. Then run again. Now all the 1.000 + 1 tempfiles should be in that tempfolder. Look at the topmost milestones.json file. Should show where things started going wrong. Then locate the folder with the faulty step. `params.json` and `milestones.json` are the input files to that step. `result.json` is what the step produces.

**Comment by thucke** [comment]
Thanks,
I'm off this weekend.
Will have a look at it then.

Am 28. Juni 2018 10:00:42 MESZ schrieb Martin Bless <notifications@github.com>:
>We should talk. I contacted you on Slack.
>The REBUILD_NEEDED is normal.
>
>What you can do: create folder `tmp-GENERATED-temp` at the same level
>of `Documentation`. Then run again. Now all the 1.000 + 1 tempfiles
>should be in that tempfolder. Look at the topmost milestones.json file.
>Should show where things started going wrong. Then locate the folder
>with the faulty step. `params.json` and `milestones.json` are the input
>files to that step. `result.json` is what the step produces.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/t3docs/docker-render-documentation/pull/5#issuecomment-400947808

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marble** [comment]
Accept the pull request(s) and you are done. We still can talk next week if you like to ;-)

**Comment by thucke** [comment]
I'd appreciate that.
Thank you a lot!

Am 28. Juni 2018 20:24:50 MESZ schrieb Martin Bless <notifications@github.com>:
>I can do an upload of the updated documentation to the docs server for
>you. If you want that. Just let me know. In that case you don't have to
>do an extra upload to TER.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/t3docs/docker-render-documentation/pull/5#issuecomment-401128789

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marble** [comment]
It is uploaded and online. But, argh, I was too cheeky ("vorlaut") - my local rendering doesn't use the perfect layout settings for the online version. In the end: Best thing would be, to merge the PR and create a new TER version.

**Comment by thucke** [comment]
Yippieh @marble,
thank you for your great support.
I've merged your PRs and made a quick rendering check with success.
Next I'll do further checks regarding the Docker/Jenkins enhancements.
I doubt I need some time ... busy at work and holiday season starts ;-)

**Comment by marble** [comment]
I'm glad I could help. It's good to know you around. Let's talk when necessary. Have a nice time!

**Pull request closed without merging**
