### PR TITLE
[DOCS] Add documentation for Gitlab CI integration

### PR DESCRIPTION
**Pull request by CDRO**
I'm currently working out how to get the container to work in giltab ci and as soon as I've got it running on my environment, I'll remove the WIP state.

### CODE REVIEW

**Comment by kaystrobach** [comment]
@cdro do you want to describe all
Options? Or do you want to provide an env var to use the options?

**Comment by CDRO** [comment]
> @CDRO do you want to describe all
> Options? Or do you want to provide an env var to use the options?

No, I'd like to describe what you can put into the jobfile and maybe how to write it on the fly if there are any magic variables or other stuff we'd like to replace on build time.

I've already documented what is available as parameters and main scripts for `mainmenu.sh`and I thought doing something similar for `jobfile.json`.

**Comment by kaystrobach** [comment]
Sound good

**Pull request merged**
